---
- name: Download nvm
  get_url: >
    url={{nvm_url}}
    dest=/tmp/nvm

- name: Install nvm
  shell: bash nvm
  args:
    chdir: /tmp
    executable: "{{zsh}}"

- name: Add activate and load NVM to .zshrc
  blockinfile:
    dest: ~/.zshrc
    marker: ''
    insertafter: EOF
    block: |
      # loads and active NVM
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
      # loads and active NVM

- name: Deeper NVM integration into .zshrc
  blockinfile:
    dest: ~/.zshrc
    marker: ''
    insertafter: EOF
    block: |
      # NVM deeper shell integration
      # Calling nvm use automatically in a directory with a .nvmrc file
      autoload -U add-zsh-hook
      load-nvmrc() {
        if [[ -f .nvmrc && -r .nvmrc ]]; then
          nvm use
        elif [[ $(nvm version) != $(nvm version default)  ]]; then
          echo "Reverting to nvm default version"
          nvm use default
        fi
      }
      add-zsh-hook chpwd load-nvmrc
      load-nvmrc
      # NVM deeper shell integration

- name: Copy global nvmrc
  copy: >
    src=nvmrc
    dest=~/.nvmrc

- name: install nodejs using nvm
  shell:
    bash -c '. /home/vagrant/.nvm/nvm.sh; nvm install '
  args:
    chdir: ~/
