---
- name: Download nvm
  get_url: url=https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh dest=/tmp/nvm

- name: Install nvm
  command: bash nvm chdir=/tmp

- name: Activate nvm
  blockinfile:
    dest: ~/.zshrc
    block: |
      autoload -U add-zsh-hook
      load-nvmrc() {
        if [[ -f .nvmrc && -r .nvmrc ]]; then
          nvm use
        elif [[ $(nvm version) != $(nvm version default)  ]]; then
          echo "Reverting to nvm default version"
          nvm use default
        fi
      }
      add-zsh-hook chpwd load-nvmrc
      load-nvmrc

- name: Copy global nvmrc
  copy: src=nvmrc dest=~/.nvmrc

- name: Install default node
  command: bash -c '. ~/.nvm/nvm.sh; nvm install '
