---
- name: Download nvm
  get_url:
    url: '{{nvm_url}}'
    dest: /tmp/nvm

- name: Install nvm
  shell: bash nvm
  args:
    chdir: /tmp
    executable: '{{zsh}}'

- name: Copy global nvmrc
  copy:
    src: nvmrc
    dest: ~/.nvmrc

- name: install nodejs using nvm
  shell: bash -c '. /home/vagrant/.nvm/nvm.sh; nvm install'
  args:
    chdir: ~/
