---
- name: update package repository and upgrade packages
  apt: update-cache=yes cache_valid_time=1800 upgrade=dist
  become: true

- name: Install common packages
  apt: name={{ item }} state=latest
  become: true
  with_items:
    - unzip
    - curl
    - wget
    - htop
    - moreutils
    - libevent-dev
    - libpq-dev
    - python-dev
    - python-psycopg2
    - tree
    - libncurses5-dev
    - libncursesw5-dev
    - upower
    - xdg-utils
