---
- name: update package repository
  apt: update-cache=yes cache_valid_time=1800
  sudo: true

- name: Install common packages
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - unzip
    - curl
    - wget
    - htop
    - moreutils
    - libevent-dev
    - libpq-dev
    - python-dev
    - python-psycopg2
