---
- name: update package repository and upgrade packages
  become: true
  apt:
    update-cache: yes
    cache_valid_time: 1800
    upgrade: dist

- name: Install common packages
  become: true
  apt:
    name: '{{ item }}'
    state: latest
  loop:
    - unzip
    - curl
    - wget
    - htop
    - moreutils
    - libevent-dev
    - libpq-dev
    - python-dev
    - python3-dev
    - python3-setuptools
    - python-psycopg2
    - tree
    - whois
    - make
    - gettext
    - upower
