---
- name: Install docker
  apt: name=docker.io
  sudo: true

- name: Create docker.io symlink
  file: src=/usr/bin/docker.io dest=/usr/local/bin/docker state=link
  sudo: true

- name: Add current user to docker group
  user: name=vagrant append=yes groups=docker
  sudo: true
  notify:
      - restart docker.io

- name: Download docker-compose
  get_url: url=https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` dest=/tmp/docker-compose

- name: Install docker-compose
  file: src=/tmp/docker-compose mode=+x 

- name: Set docker-compose globally
  copy: src=/tmp/docker-compose dest=/usr/local/bin/docker-compose
