---
- name: Add docker gpg key
  become: true
  apt_key:
    url: '{{docker_keyserver}}'
    id: '{{docker_key}}'

- name: Add docker entry for ubuntu
  become: true
  apt_repository:
    repo: '{{docker_source}}'
    filename: docker.list

- name: update package repository and upgrade packages
  become: true
  apt:
    update-cache: yes
    upgrade: dist

- name: Install docker
  become: true
  apt:
    name: docker-ce
    state: present

- name: Add current user to docker group
  become: true
  user:
    name: vagrant
    append: yes
    groups: docker
  notify:
  - restart docker

- name: Download docker-compose
  become: true
  get_url:
    url: '{{docker_compose_url}}'
    dest: '{{docker_compose_path}}'
    mode: +x

- name: Download nfs plugin
  become: yes
  get_url:
    url: https://github.com/ContainX/docker-volume-netshare/releases/download/v0.34/docker-volume-netshare_0.34_amd64.deb
    dest: /opt/docker-volume-netshare.deb

- name: Install nfs plugin
  become: yes
  apt:
    deb: /opt/docker-volume-netshare.deb
  notify:
    - restart nfs
