---
- name: Install docker
  apt: name=docker.io
  sudo: true

- name: Create docker.io symlink
  file: src=/usr/bin/docker.io dest=/usr/local/bin/docker state=link
  sudo: true

- name: Add current user to docker group
  user: name=vagrant append=yes groups=docker
  sudo: true
  notify:
      - restart docker.io

- name: Fetch kernel name
  shell: uname -s
  ignore_errors: yes
  register: kernel

- name: Fetch machine hardware name
  shell: uname -m
  ignore_errors: yes
  register: machine

- name: Download docker-compose
  get_url: url=https://github.com/docker/compose/releases/download/1.7.1/docker-compose-{{ kernel.stdout }}-{{ machine.stdout }} dest=/tmp/docker-compose

- name: Set docker-compose permissions
  file: path=/tmp/docker-compose mode=0755

- name: Set global docker-compose command
  command: mv /tmp/docker-compose /usr/local/bin/docker-compose
  sudo: true
