---
- name: Install docker
  apt: name=docker.io
  sudo: true

- name: Create docker.io symlink
  file: src=/usr/bin/docker.io dest=/usr/local/bin/docker state=link
  sudo: true

- name: Add current user to docker group
  user: name=vagrant append=yes groups=docker
  sudo: true
  notify:
      -restart docker.io

- name: Install python-dev dependecy
  command: apt-get install -y python-dev
  sudo: true

- name: Install libenvet dev dependecy
  command: apt-get install -y libevent-dev
  sudo: true 

- name: Install fig to manage docker
  command: pip install -U fig
  sudo: true
