---
- name: Ensure apt-transport-https ca-certificates are installed
  become: true
  apt:
    name: '{{ item }}'
    state: latest
  loop:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add docker gpg key
  become: true
  apt_key:
    url: '{{docker_keyserver}}'
    id: '{{docker_key}}'

- name: Add docker entry for ubuntu
  become: true
  apt_repository:
    repo: '{{docker_source}}'
    filename: docker.list

- name: update package repository and upgrade packages
  become: true
  apt:
    update-cache: yes
    upgrade: dist

- name: Install docker
  become: true
  apt:
    name: docker-ce

- name: Add current user to docker group
  become: true
  user:
    name: vagrant
    append: yes
    groups: docker
  notify:
  - restart docker

- name: Download docker-compose
  become: true
  get_url:
    url: '{{docker_compose_url}}'
    dest: '{{docker_compose_path}}'

- name: Set docker-compose permissions
  become: true
  file:
    path: '{{docker_compose_path}}'
    mode: 0755
