---
- name: Install java
  become: true
  apt: >
    name={{ item }}
    state=latest
  with_items:
    - openjdk-7-jdk
    - ant
    - gradle
    - maven
    - lib32ncurses5
    - lib32gomp1
    - lib32z1-dev
    - lib32ncurses5
    - lib32gomp1
    - lib32z1-dev

- name: Download Android SDK
  get_url:
    url={{android_url}}
    dest=/tmp

- name: Untar Android SDK
  become: yes
  unarchive: >
    src=/tmp/{{android_url | basename}}
    dest=/opt

- name: Get user name
  shell: id -u -n
  register: user_name

- name: Get user group
  shell: id -g -n
  register: user_group

- name: Set sdk folder permissions
  become: true
  file:
    path=/opt/android-sdk-linux
    recurse=yes
    state=directory
    owner={{ user_name.stdout }}
    group={{ user_group.stdout }}

- name: set android variables
  blockinfile:
    dest: ~/.zshrc
    marker: ''
    insertafter: EOF
    block: |
      # android variables
      export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
      export ANDROID_HOME=/opt/android-sdk-linux
      export ANDROID_TOOLS=$ANDROID_HOME/tools/
      export ANDROID_PLATFORM_TOOLS=$ANDROID_HOME/platform-tools/
      export PATH=$PATH:$ANDROID_TOOLS:$ANDROID_PLATFORM_TOOLS
      # android variables

- name: Install android platform-tools
  shell: "echo y | /opt/android-sdk-linux/tools/android update sdk --no-ui --all --filter {{ item }}"
  with_items:
    - "tools"
    - "platform-tools"
    - "build-tools-24"
    - "build-tools-23.0.3"
    - "build-tools-22.0.1"
    - "android-23"
    - "android-22"
    - "android-21"
    - "extra-android-support"
    - "extra-google-m2repository"
    - "extra-google-google_play_services"
    - "extra-android-m2repository"
