---
- name: Install zsh
  apt:
    name: zsh
  become: yes

- name: Clone oh-my-zsh repo
  git:
    repo: '{{zsh_repo}}'
    dest: ~/.oh-my-zsh

- name: symlink zshrc
  file:
    src: /vagrant/provisioning/roles/zsh/files/zshrc
    dest: ~/.zshrc
    state: link

- name: Set zsh as default shell
  become: yes
  user:
    shell: /bin/zsh
    name: vagrant

- name: Download theme
  git:
    repo: '{{bullet_repo}}'
    dest: ~/.oh-my-zsh/custom/themes/bullet-train

- name: Create symlink to theme
  file:
    src: ~/.oh-my-zsh/custom/themes/bullet-train/bullet-train.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/bullet-train.zsh-theme
    state: link
