---
- name: Install zsh
  apt: name=zsh
  become: true

- name: Clone oh-my-zsh repo
  git: >
    repo={{zsh_repo}}
    dest=~/.oh-my-zsh

- name: symlink zshrc
  copy: >
   src=zshrc
   dest=~/.zshrc

- name: Set zsh as default shell
  become: true
  user: >
    shell=/bin/zsh
    name=vagrant

- name: Download theme
  git: >
   repo={{bullet_repo}}
   dest=~/.oh-my-zsh/custom/themes/bullet-train

- name: Create symlink to theme
  file: >
    src=~/.oh-my-zsh/custom/themes/bullet-train/bullet-train.zsh-theme
    dest=~/.oh-my-zsh/custom/themes/bullet-train.zsh-theme
    state=link
