# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# fix for zsh theme
ZSH_DISABLE_COMPFIX=true

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="bullet-train"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=5

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-nvm tmux pip python virtualenv virtualenvwrapper pipenv docker-compose)
plugins+=(zsh-navigation-tools npm ssh-agent git-flow docker npx)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

# BULLETTRAIN
BULLETTRAIN_PROMPT_ORDER=(time status dir git nvm virtualenv)
BULLETTRAIN_PROMPT_CHAR=→
BULLETTRAIN_NVM_PREFIX=♦
BULLETTRAIN_VIRTUALENV_PREFIX=@
BULLETTRAIN_TIME_12HR=false
BULLETTRAIN_STATUS_EXIT_SHOW=true
BULLETTRAIN_EXEC_TIME_SHOW=true
BULLETTRAIN_DIR_EXTENDED=1
BULLETTRAIN_GIT_AHEAD=↑
BULLETTRAIN_GIT_BEHIND=↓
# ENDBULLETTRAIN

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
export EDITOR='vim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
alias vimrc="vim ~/.vimrc"
alias zshrc="vim ~/.zshrc"
alias dc="docker-compose"

# term color
# export TERM="xterm-256color"

# tmux fix for colors
alias tmux='tmux -2'

# virtualenv workon_home variable
export WORKON_HOME=$HOME/.virtualenvs
# virtualenv workon_home variable

# Project home for virtualenvwrapper
export PROJECT_HOME=$HOME/repos
# Project home for virtualenvwrapper

# virtualenv source
source /usr/local/bin/virtualenvwrapper.sh
# virtualenv source

# virtualenv workon_home variable
source /usr/local/bin/aws_zsh_completer.sh
# virtualenv workon_home variable

# zsh widget biding for history, places and kill
autoload znt-history-widget
zle -N znt-history-widget
bindkey "^R" znt-history-widget
zle -N znt-cd-widget
bindkey "^S" znt-cd-widget
zle -N znt-kill-widget
bindkey "^Y" znt-kill-widget

# tmuxinator completion
source ~/.bin/tmuxinator.zsh
# tmuxinator completion

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# loads and active NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
# loads and active NVM

# NVM deeper shell integration
# Calling nvm use automatically in a directory with a .nvmrc file
#autoload -U add-zsh-hook
#load-nvmrc() {
#  if [[ -f .nvmrc && -r .nvmrc ]]; then
#    nvm use
#  elif [[ $(nvm version) != $(nvm version default)  ]]; then
#    echo "Reverting to nvm default version"
#    nvm use default
#  fi
#}
#add-zsh-hook chpwd load-nvmrc
#load-nvmrc
# NVM deeper shell integration

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
