- name: Install global pip packages
  become: true
  shell: pip install {{ item }}
  args:
    executable: "{{zsh}}"
  with_items:
    - awscli

- name: Add AWS autocompleter to zshrc
  blockinfile:
    dest: ~/.zshrc
    create: yes
    marker: ''
    insertafter: EOF
    block: |
      # virtualenv workon_home variable
      source /usr/local/bin/aws_zsh_completer.sh
      # virtualenv workon_home variable
