---
- name: Install tmux necessary packages
  become: true
  apt:
   name: '{{ item }}'
   state: latest
  loop:
    - tmux

- name: Symlink settings
  file:
    src: /vagrant/provisioning/roles/tmux/files/tmux.conf
    dest: ~/.tmux.conf
    state: link

- name: Install tmux package manager
  git:
   repo: '{{tpm}}'
   dest: ~/.tmux/plugins/tpm

- name: Reload TMUX environment so TPM is sourced
  shell: tmux source ~/.tmux.conf
  ignore_errors: True
  args:
    executable: '{{zsh}}'
