---
- name: Add tmux ppa
  apt_repository: repo='ppa:pi-rho/dev'
  sudo: true

- name: Install tmux from package repository
  apt: name=tmux state=latest update_cache=yes
  sudo: true

- name: Copy settings
  copy: src=tmux.conf dest=~/.tmux.conf

- name: Install tmux package manager
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm
