---
- name: Download latest pip
  get_url:
    url: https://bootstrap.pypa.io/{{ pip_file }}
    dest: /tmp

- name: Install pip
  become: yes
  command: python {{ pip_file }}
  args:
    chdir: /tmp

- name: Install global pip packages
  command: pip install {{ item }}
  become: yes
  with_items:
    - flake8
    - virtualenv
    - virtualenvwrapper
    - awscli
    - pipenv

- name: Install lib packages
  become: yes
  apt:
    name: [
      python-psycopg2,
      python3-distutils,
      python3-dev,
      python3-setuptools,
      libpq-dev,
      python-dev,
      libjpeg-dev,
      libmemcached-dev,
      zlib1g-dev,
      python3.8
    ]
    state: latest
