---
- name: Download latest pip
  get_url:
    url: https://bootstrap.pypa.io/{{ pip_file }}
    dest: /tmp

- name: Install pip
  become: true
  shell: python {{ pip_file }}
  args:
    chdir: /tmp
    executable: '{{zsh}}'

- name: Install global pip packages
  become: true
  shell: pip install {{ item }}
  args:
    executable: '{{zsh}}'
  loop:
    - flake8
    - virtualenv
    - virtualenvwrapper
    - awscli

- name: Install postgres system packages
  become: true
  apt:
    name: '{{ item }}'
    state: latest
  loop:
      - python-psycopg2
      - libpq-dev
      - python-dev
      - libjpeg-dev
      - libmemcached-dev
