---
- name: Download latest pip
  get_url: url=https://bootstrap.pypa.io/{{ pip_file }} dest=/tmp

- name: Install pip
  command: python {{ pip_file }} chdir=/tmp
  sudo: true

- name: Install global pip packages
  command: pip install {{ item }}
  sudo: true
  with_items:
    - flake8
    - virtualenv
    - virtualenvwrapper

- name: Add workon_home variable for virtualenvwrapper
  lineinfile: line='export WORKON_HOME=$HOME/.virtualenvs' dest=~/.zshrc create=yes

- name: Add project_home variable for virtualenvwrapper
  lineinfile: line='export PROJECT_HOME=$HOME/repos' dest=~/.zshrc create=yes

- name: Source virtualenvwrapper
  lineinfile: line="source /usr/local/bin/virtualenvwrapper.sh" dest=~/.zshrc state=present create=yes
  
- name: Install postgres system packages
  apt: name={{ item }} state=latest
  with_items:
      - python-psycopg2
      - libpq-dev
      - python-dev
  sudo: true
