---
- name: Import keys
  shell: gpg --keyserver {{rvm}}
  args:
    executable: "{{zsh}}"

- name: Download rvm
  get_url: >
   url=https://get.rvm.io
   dest=/tmp/rvm

- name: Install rvm
  shell: bash rvm stable --ruby=1.9.3
  args:
    chdir: /tmp
    executable: "{{zsh}}"

- name: Install global gems
  shell: bash -lc "gem install {{item}}"
  with_items:
    - tmuxinator
  args:
    executable: "{{zsh}}"

- name: Create .bin directory to hold tmuxinator.zsh completion
  file: >
    path=~/.bin
    state=directory

- name: Download completion file from the repo
  get_url: >
    url={{mux_completion}}
    dest=~/.bin/

- name: Add tmuxinator to zshrc
  blockinfile:
    dest: ~/.zshrc
    marker: ''
    insertafter: EOF
    block: |
      # tmuxinator completion
      source ~/.bin/tmuxinator.zsh
      # tmuxinator completion
