---
- name: Prepare the system
  become: true
  apt:
    name: software-properties-common
    state: latest

- name: Add PPA
  become: true
  apt_repository:
    repo: ppa:rael-gc/rvm
    state: present

- name: update package repository and upgrade packages
  become: true
  apt:
    update-cache: yes
    upgrade: dist

- name: Install rvm
  become: true
  apt:
    name: rvm
    state: latest

- name: Add current user to rvm group
  become: true
  user:
    name: vagrant
    append: yes
    groups: rvm

- name: Create .bin directory to hold tmuxinator.zsh completion
  file:
    path: ~/.bin
    state: directory

- name: Download completion file from the repo
  get_url:
    url: "{{mux_completion}}"
    dest: ~/.bin/
