---
- name: Install vim from package repository
  apt:
    name: '{{ item }}'
    state: latest
  become: true
  loop:
    - vim
    - exuberant-ctags
    - ack-grep

# Download settings from own repository
- name: Download vim folder
  git:
    repo: '{{vim_repo}}'
    dest: ~/.vim
    force: yes

- name: Create symlink to vimrc
  file:
    src: ~/.vim/.vimrc
    dest: ~/.vimrc
    state: link

- name: Create symlink to pathogen
  file:
    src: ~/.vim/autoload/vim-pathogen/autoload/pathogen.vim
    dest: ~/.vim/autoload/pathogen.vim
    state: link

- name: Create symlink to hybrid theme
  file:
    src: ~/.vim/colors/hybrid/colors/hybrid.vim
    dest: ~/.vim/colors/hybrid.vim
    state: link
